# .github/workflows/ci.yml

name: Continuous Integration Workflow

# Trigger this workflow whenever a new PR is created on the main branch
on: 
    pull_request: 
        branches: main

# Set some defaults
defaults:
    run:
        shell: bash
        working-directory: ./
        
# Jobs run in parallel by default
jobs:
    test:
        name: 'Run unit tests'
        runs-on: ubuntu-latest

        strategy:
          matrix:
            # Define multiple Node.js versions here
            node-version: [14.x, 16.x, 18.x, 20.x] 

        steps:
            - uses: actions/checkout@v4
              name: 'Checkout repository'

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'yarn'
            
            - name: 'Install Dependencies'
              run: yarn

            - name: 'Run tests'
              run: yarn test
    lint:                                     
        name: 'Run linter'                    
        runs-on: ubuntu-latest 

        strategy:
          matrix:
            # Define multiple Node.js versions here
            node-version: [14.x, 16.x, 18.x, 20.x] 

        steps:                                
            - uses: actions/checkout@v4       
              name: 'Checkout repository'     
            
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'yarn'

            - name: 'Install Dependencies'    
              run: yarn                     
                                              
            - name: 'Run linter'              
              run: yarn lint
