#  .github/workflows/npm-publish.yml 

name: Publish a Node.js Package to the NPM registry

# Trigger this workflow whenever a new PR is closed on the main branch
on:
    # Allows you to trigger this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'yarn'
                registry-url: https://registry.npmjs.org/
            
            - name: Fetch the latest artifact
              run: |
                  ARTIFACT_URL=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
                    | jq -r '.artifacts[0].archive_download_url')
                  echo "Artifact URL: $ARTIFACT_URL"
          
            - name: Download and extract artifact
              run: |
                  curl -L -o artifact.zip -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $ARTIFACT_URL
                  unzip artifact.zip -d dist/
                           
            - run: |
                npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}