#  .github/workflows/npm-publish.yml 

name: Publish a Node.js Package to the NPM registry

# Trigger this workflow whenever a new PR is closed on the main branch
on:
    # Allows you to trigger this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'yarn'
                registry-url: https://registry.npmjs.org/

            # - name: Download build artifact
            #   uses: actions/download-artifact@v4
            #   with:
            #     name: ts-build
            #     path: dist/

            # - name: Download build artifact
            #   uses: actions/download-artifact@v4
            #   with:
            #       name: ts-build
            #       run-id: ${{ github.event.workflow_run.id }}
            #       github-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Get latest workflow run number
              run: |
                LATEST_RUN=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=1" \
                | jq '.workflow_runs[0].run_number')
                echo "The latest workflow run number is $LATEST_RUN"

            - name: Log workflow_run.id 
              run: echo '${{ toJSON(github.event) }}' 
              shell: bash
            
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                name: ts-build
                github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
                repository: YarivGilad/timescript3
                run-id: 10

            - run: |
                npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}